### ISSUE TITLE
How was `css/hl.css` generated?

### ISSUE THREAD

**Issue by philderbeast** [Fresheyeball/haskell.org-hakyll#1]
@Fresheyeball do you have access to the sources or can you remember how `css/hl.css` was generated?

I'd like to reuse some of these styles for Cabal's with  https://github.com/haskell/cabal-website/issues/5.

Some of the CSS is coming from bootstrap, isn't it?

![image](https://github.com/Fresheyeball/haskell.org-hakyll/assets/633283/7f66df06-7e65-47ca-9810-7d48bc756cf6)

**Comment by Fresheyeball** [comment]
I believe I modified it from somewhere. I don't recall. Its been about 5 years.
